### ISSUE TITLE
feat: add missing options

### ISSUE THREAD

**Issue by Hunter-Thompson** [opencdk8s/cdk8s-argocd-resources#1]
- [ ] helm parameters for Application
- [ ] kustomize parameters for Application
- [ ] jsonnet parameters for Application
- [ ] ignoreDifferences parameters for Application
- [ ] jwtTokens parameters for AppProject
- [ ] role parameters for AppProject

**Comment by airmonitor** [comment]
Hello.

I'm wondering if helm and kustomize integration will be implemented?

Regards
Tom

**Comment by Hunter-Thompson** [comment]
> Hello.
> 
> I'm wondering if helm and kustomize integration will be implemented?
> 
> Regards Tom

Contributions are welcome : )

**Comment by airmonitor** [comment]
happy to help.

I know python :)

**Comment by Hunter-Thompson** [comment]
> happy to help.
> 
> I know python :)

It would be as simple as mapping the exact types of the missing options, inside interfaces.

Please go through [this](https://www.typescriptlang.org/docs/handbook/2/objects.html) to get an idea on how to work with interfaces and types in Typescript. Il be happy to help, and review your PR.
